services:

  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"
      - "81:81/tcp"
      - "853:853/tcp"
      - "784:784/tcp"
      - "8853:8853/tcp"
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf
    environment:
      TZ: "Europe/Berlin"

volumes:
  adguard-work:
  adguard-conf:
